name: github-actions
services:
  runner:
    image: ghcr.io/albercldev/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./store:/actions-runner/.store
    env_file:
      - .env
