name: github-actions
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./store:/actions-runner/.store
    env_file:
      - .env
